name: Deployment Workflow

on: 
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ID_RSA }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Get files
        uses: actions/checkout@v2
      - name: Example
        run: |
          echo $ pwd
          pwd
          echo $ ls -la
          ls -la
          echo $ ssh diagonal@cassini.cs.kent.edu ls -la
          ssh diagonal@cassini.cs.kent.edu ls -la
